# Default values for knative-serving.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

knative-serving: 
  replicaCount: 2

  name: knative-serving
  namespace: knative-serving